### ISSUE TITLE
Definitions conflict on run after initial install

### ISSUE THREAD

**Issue by consciousweb** [firelayer/firelayer#10]
### I'm submitting a Bug Report
init according to docs crashes, citing duplicate definitions for firestore. 

### `firelayer-debug.log` and CLI `firelayer info` output: 

```
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Not Found
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @firelayer/cli: ^1.1.0 => 1.1.0 
    @firelayer/core:  1.1.0 
  npmGlobalPackages:
    @firelayer/cli: 1.1.0
    firelayer: Not Found

insert the content of firelayer-debug.log if relevant
```

```
insert the output from firelayer info here
```

### Current behavior:

follow the getting started instructions, and upon running "npm run dev"

cli error output:

> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/firestore.d.ts(23,1): error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, v1beta1, v1, OK, CANCELLED, UNKNOWN, INVALID_ARGUMENT, DEADLINE_EXCEEDED, NOT_FOUND, ALREADY_EXISTS, PERMISSION_DENIED, RESOURCE_EXHAUSTED, FAILED_PRECONDITION, ABORTED, OUT_OF_RANGE, UNIMPLEMENTED, INTERNAL, UNAVAILABLE, DATA_LOSS, UNAUTHENTICATED, FirebaseFirestore
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/firestore.d.ts(166,5): error TS2374: Duplicate string index signature.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/firestore.d.ts(1680,8): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1/firestore_admin_client.d.ts(538,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1/firestore_admin_client.d.ts(641,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1/firestore_client.d.ts(611,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1/firestore_client.d.ts(766,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1/firestore_client.d.ts(859,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1beta1/firestore_client.d.ts(616,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1beta1/firestore_client.d.ts(775,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/@google-cloud/firestore/types/v1beta1/firestore_client.d.ts(872,6): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/google-gax/build/src/operationsClient.d.ts(246,111): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/google-gax/build/src/paginationCalls/pageDescriptor.d.ts(41,83): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@firelayer/core/node_modules/google-gax/build/src/paginationCalls/pageDescriptor.d.ts(42,84): error TS2304: Cannot find name 'AsyncIterable'.
> node_modules/@google-cloud/firestore/types/firestore.d.ts(23,1): error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, v1beta1, v1, OK, CANCELLED, UNKNOWN, INVALID_ARGUMENT, DEADLINE_EXCEEDED, NOT_FOUND, ALREADY_EXISTS, PERMISSION_DENIED, RESOURCE_EXHAUSTED, FAILED_PRECONDITION, ABORTED, OUT_OF_RANGE, UNIMPLEMENTED, INTERNAL, UNAVAILABLE, DATA_LOSS, UNAUTHENTICATED, FirebaseFirestore
> node_modules/firebase-functions/lib/providers/https.d.ts(109,25): error TS2694: Namespace 'admin' has no exported member 'appCheck'.

### Expected behavior:

runs

### Steps to reproduce:

install according docs, and run "npm run dev"

**Comment by jpntex** [comment]
@consciousweb Firebase dependencies updated and locked for all templates 247fa647c99783f8f51ddcc0d70961d88fc73cb7.
Let me know if it's still happening with the new release v1.1.1
