### ISSUE TITLE
NPM RUN DEV Not working. Vue-cli-service is failing

### ISSUE THREAD

**Issue by Utitofon-Udoekong** [firelayer/firelayer#11]
### `firelayer-debug.log` and CLI `firelayer info` output: 

```
insert the content of firelayer-debug.log if relevant
```
[init | Fri, 30 Jul 2021 21:57:00 GMT]: Error: Error: npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@firebase%2fauth: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-07-30T21_57_00_114Z-debug.log

Error: Error: npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@firebase%2fauth: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-07-30T21_57_00_114Z-debug.log

    at Object.exports.default (C:\Users\user\AppData\Roaming\npm\node_modules\@firelayer\cli\dist\helpers\install.js:141:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Init.run (C:\Users\user\AppData\Roaming\npm\node_modules\@firelayer\cli\dist\commands\init.js:31:13)
    at async Init._run (C:\Users\user\AppData\Roaming\npm\node_modules\@firelayer\cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Config.runCommand (C:\Users\user\AppData\Roaming\npm\node_modules\@firelayer\cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\user\AppData\Roaming\npm\node_modules\@firelayer\cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\user\AppData\Roaming\npm\node_modules\@firelayer\cli\node_modules\@oclif\command\lib\command.js:43:20)

```
insert the output from firelayer info here
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) ia32 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.20.3 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.18362.387.0)
  npmPackages:
    @firelayer/cli: ^1.1.1 => 1.1.1
    @firelayer/core:  1.1.1
  npmGlobalPackages:
    @firelayer/cli: Not Found
    firelayer: Not Found

### Current behavior:

![Screenshot_3](https://user-images.githubusercontent.com/69417647/127721228-7b2a2d72-dc83-44b0-944d-adf23cd2d41f.png)

### Steps to reproduce:

npm i
npm run dev

**Comment by jpntex** [comment]
@Utitofon-Udoekong I think something went with the network while trying to install dependencies. Are you connected to the Internet while trying this and your access is not block by the service provider or something?

**Comment by Utitofon-Udoekong** [comment]
I'm working with a stable network. There is no network blocker on my system
