### ISSUE TITLE
Cannot sign up for newsletter!

### ISSUE THREAD

**Issue by tohagan** [firelayer/firelayer#4]
### I'm submitting a ...

[x ] Bug Report

### Current behavior:

Cannot sign up to your newsletter online as it only accepts email domains with ".com", mine uses ".name".
- https://firelayer.io/

### Expected behavior:

Should allow all [top level domains](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains).

**Comment by jpntex** [comment]
Thanks for reporting, I've created the [issue](https://github.com/firelayer/firelayer.io/issues/4) in the firelayer.io repository.
